# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
