# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(default='2', max_length=200, null=True),
        ),
    ]
