# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170713_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
