# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170713_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
